version: '2'

services:

  test:
    build:
      context: .
      # should actually be Dockerfile.test
      dockerfile: Dockerfile.base
    depends_on:
      - test_db
    # volumes:
    #   - django_proj:/deploy/app
  web:
    build:
      context: .
      dockerfile: Dockerfile.production

    # depends_on:
    #   - db
      # - cache
    ports:
      - "8000:8000"

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb

  test_db:
    image: postgres:9.6
    # TODO: could use a custom extended package if it makes sense
    # to do so
    # build: postgres:9.6
    # build:
    #   context: .
    #   dockerfile: Dockerfile.postgres

    environment:
      - POSTGRES_USER=test_django
      - POSTGRES_PASSWORD=test_django
      - POSTGRES_DB=test_django
      

    # image: postgres:9.6
    # TODO: Add container as well
    # volumes_from:
    #   - container:dbstore
    # volumes:
    #   - pgvolume: /var/lib/postgresql/data

    # environment:
    #   - POSTGRES_USER="test_django"
    #   - POSTGRES_PASSWORD="test_django"
    #   - POSTGRES_DB="test_django"

  # TODO: Add other types of databases
  # db:
  #   image: postgres
  # cache:
  #   image: redis

# volumes:
#   pgvolume: #declare a volume named pgvolume
