FROM andreacrotti/infrastructure-samples
MAINTAINER Andrea <andrea.crotti.0@gmail.com>

COPY requirements_test.txt .
RUN pip install -r requirements.txt

COPY docker_test.sh /

#TODO: the database url could be constructed from the other env variables
# ENV DATABASE_URL "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@test_db/$POSTGRES_DB"
ENV DATABASE_URL "postgres://test_django:test_django@test_db:5432/test_django"
ENV KEEP_DB 1

#TODO: the 1 should come from KEEP_DB instead
CMD ["/docker_test.sh"]
