version: '2'

services:
  pypiserver:
    build:
      context: .
      dockerfile: Dockerfile.pypiserver

  test:
    build:
      context: .
      # should actually be Dockerfile.test
      dockerfile: Dockerfile.base

    depends_on:
      - test_db
      - mongodb

    volumes:
      - ./reports:/deploy/app/reports

  web:
    build:
      context: .
      dockerfile: Dockerfile.production

    ports:
      - "8000:8000"

  mongodb:
    image: mongo:3.2

  test_db:
    # keep in mind that you can't change super easily from one version to
    # the other if there are volumes involved
    image: postgres:9.5
    # TODO: could use a custom extended package if it makes sense

    environment:
      - POSTGRES_USER=test_django
      - POSTGRES_PASSWORD=test_django
      - POSTGRES_DB=test_django

    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  reports:
