FROM ubuntu:16.04
MAINTAINER Andrea <andrea.crotti.0@gmail.com>

ENV PYTHONUNBUFFERED 1

RUN apt-get -qy update && apt-get install -y \
    python \
    python-pip

RUN mkdir -p /pypyserver/packages
WORKDIR /pypyserver

RUN pip install pypiserver

EXPOSE 9100
CMD ["pypi-server", "/pypyserver/packages"]

